"""Generate the transcript the README shows.

CI reruns this and fails if the committed output no longer matches what the code
produces (gate G5). The committed artifact IS the claim, same as the four labs.

    python tools/demo.py            # print
    python tools/demo.py --write    # regenerate docs/TRANSCRIPT.md
"""
from __future__ import annotations

import argparse
import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from oncall_router import tools                     # noqa: E402
from oncall_router.catalog import Catalog           # noqa: E402

SCENES = [
    ("A page fires and nobody recognises the service name",
     "who_owns", {"service": "the gateway"}),
    ("The same question, for a service this catalog has never heard of",
     "who_owns", {"service": "billing-engine"}),
    ("It is a sev1. Who are we waking, and by when?",
     "escalation_path", {"service": "api-gateway", "severity": "sev1"}),
    ("Somebody types a severity that does not exist",
     "escalation_path", {"service": "api-gateway", "severity": "sev9"}),
    ("What does the runbook say about latency here?",
     "playbook", {"service": "gateway", "symptom": "latency"}),
    ("Impact started at 14:00. It is now 14:22. Where should we be?",
     "impact_clock", {"service": "api-gateway", "severity": "sev1",
                      "impact_start": "2026-08-23T14:00:00Z",
                      "now": "2026-08-23T14:22:00Z"}),
    ("The ticket was opened at 14:30 for both, but impact started 28 minutes apart",
     "impact_clock", {"service": "api-gateway", "severity": "sev1",
                      "impact_start": "2026-08-23T14:02:00Z",
                      "now": "2026-08-23T14:30:00Z"}),
]


def render(cat: Catalog) -> str:
    out = io.StringIO()
    out.write("# Transcript\n\n")
    out.write("Generated by `python tools/demo.py --write`. CI regenerates this file and\n")
    out.write("fails the build if it no longer matches what the code produces.\n")
    for title, name, args in SCENES:
        out.write(f"\n## {title}\n\n")
        out.write("```\n")
        out.write(f"{name}({json.dumps(args)[1:-1]})\n")
        out.write("```\n\n```json\n")
        fn = getattr(tools, name)
        result = fn(cat, *_positional(name, args))
        out.write(json.dumps(result, indent=2))
        out.write("\n```\n")
    return out.getvalue()


def _positional(name: str, args: dict) -> list:
    if name == "who_owns":
        return [args["service"]]
    if name == "escalation_path":
        return [args["service"], args["severity"]]
    if name == "playbook":
        return [args["service"], args.get("symptom")]
    if name == "impact_clock":
        return [args["service"], args["severity"], args["impact_start"], args.get("now")]
    raise ValueError(name)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ns = ap.parse_args()
    text = render(Catalog.load(ROOT / "catalog.toml"))
    target = ROOT / "docs" / "TRANSCRIPT.md"
    if ns.write:
        target.parent.mkdir(exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {target.relative_to(ROOT)} ({len(text)} chars)")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
